# Generated by Django 2.0.2 on 2018-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ユーザーID')),
                ('passport', models.CharField(db_index=True, max_length=50, verbose_name='パスポートハッシュ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='認証先')),
                ('type_id', models.CharField(max_length=255, verbose_name='認証先ID')),
                ('name', models.CharField(max_length=50, verbose_name='ユーザー名')),
                ('user_dir', models.CharField(max_length=20, verbose_name='ユーザーディレクトリ名')),
                ('access_token_key', models.CharField(max_length=255, verbose_name='アクセストークン(key)')),
                ('access_token_secret', models.CharField(max_length=255, verbose_name='アクセストークン(secret)')),
                ('page_id', models.IntegerField(default=0, verbose_name='現在のページ')),
                ('sync_flag', models.BooleanField(default=1, verbose_name='同期対象')),
                ('use_mobile', models.BooleanField(default=0, verbose_name='モバイル版を使用してるかどうか')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('type', 'type_id')},
        ),
        migrations.AlterUniqueTogether(
            name='passport',
            unique_together={('user_id', 'passport')},
        ),
    ]
