# Generated by Django 2.0.2 on 2018-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ユーザーID')),
                ('mobile_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='スマホ版のID')),
                ('category_id', models.IntegerField(verbose_name='カテゴリID')),
                ('name', models.CharField(default=0, max_length=200, verbose_name='Bookmark名')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort番号')),
                ('sync_flag', models.BooleanField(default=1, verbose_name='同期対象')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ユーザーID')),
                ('mobile_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='スマホ版のID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('angle', models.IntegerField(default=0, verbose_name='位置')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort番号')),
                ('color_id', models.IntegerField(default=18, verbose_name='カテゴリカラーID')),
                ('tag_open', models.BooleanField(default=1, verbose_name='初期開放')),
                ('sync_flag', models.BooleanField(default=1, verbose_name='同期対象')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カラー名')),
                ('thumbnail_color_code', models.CharField(max_length=10, verbose_name='選択サムネイル_カラーコード')),
                ('color_code1', models.CharField(max_length=10, verbose_name='カラーコード1')),
                ('color_code2', models.CharField(max_length=10, verbose_name='カラーコード2')),
                ('color_code3', models.CharField(max_length=10, verbose_name='カラーコード3')),
                ('font_color', models.CharField(max_length=10, verbose_name='fontカラー')),
                ('icon_color', models.CharField(default='white', max_length=10, verbose_name='iconカラー')),
                ('sort', models.IntegerField(verbose_name='順番')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeleteManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ユーザーID')),
                ('bookmark', models.TextField(blank=True, null=True, verbose_name='ブックマークの削除ID')),
                ('category', models.TextField(blank=True, null=True, verbose_name='カテゴリの削除ID')),
                ('page', models.TextField(blank=True, null=True, verbose_name='ページの削除ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ユーザーID')),
                ('linkmark_flg', models.BooleanField(default=0, verbose_name='リンクマーク')),
                ('link_color', models.CharField(default='#005580', max_length=10, verbose_name='リンク色')),
                ('category_back_color', models.CharField(default='#FFF', max_length=10, verbose_name='カテゴリ背景色')),
                ('portal_back_kind', models.BooleanField(default=0, verbose_name='画面背景設定')),
                ('portal_back_color', models.CharField(default='#FFF', max_length=10, verbose_name='画面背景色')),
                ('image_position', models.CharField(max_length=30, verbose_name='画像の配置')),
                ('bk_image_ext', models.CharField(max_length=30, null=True, verbose_name='背景画像の拡張子')),
                ('sync_flag', models.BooleanField(default=1, verbose_name='同期対象')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ユーザーID')),
                ('mobile_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='スマホ版のID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('category_ids_str', models.TextField(verbose_name='ページに含むカテゴリ')),
                ('angle_ids_str', models.TextField(blank=True, null=True, verbose_name='ページに含むカテゴリ位置')),
                ('sort_ids_str', models.TextField(blank=True, null=True, verbose_name='ページに含むカテゴリ順番')),
                ('sync_flag', models.BooleanField(default=1, verbose_name='同期対象')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
