# Generated by Django 2.0.2 on 2018-02-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='bookmark',
            index_together={('user_id', 'category_id'), ('user_id', 'sync_flag')},
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together={('user_id', 'angle'), ('user_id', 'sync_flag')},
        ),
        migrations.AlterIndexTogether(
            name='page',
            index_together={('user_id', 'sync_flag')},
        ),
    ]
